### ISSUE TITLE
The code about compute flow

### ISSUE THREAD

**Issue by longmao-yiran** [mzolfaghari/chained-multistream-networks#2]
hello:
      Fast of all ,thank you for sharing your work. I've read your article and it's great. 
      And I want to follow you work. According to the paper,"We compute the optical flow with the method from Zach et al. [52], which is a reliable variational method that runs sufficiently fast", it means you use the method called TV-L1 to compute flow. I found that opencv implements this metho. Then I use the function in opencv3.3 to compute flow and train network ,but the effect is not good. I compared the optical flow images which I extracted and the optical flow images listed in the paper, I find the optical flow images which I extracted have more noise. Could you please upload the code that you calculate the optical flow image?
      Looking forward to your reply.

**Comment by mzolfaghari** [comment]
Hi Longmao,

Thanks for your interest on our work. We used [this](https://github.com/yjxiong/dense_flow) implementation for computing optical flow.

In addition we converted the optical flow components into a 3-channel RGB image by stacking components and their magnitude. The script for this conversion will be available soon.

Best,
