### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by happyday521** [mzolfaghari/chained-multistream-networks#3]
I want to create body maps on UCF101 using your code，can you provide me with the RGB mean or how could I get the mean value? Thanks! Expect your response！

**Comment by mzolfaghari** [comment]
Hi @tangjilin 

To create  body maps you can use the following code:
https://github.com/mzolfaghari/chained-multistream-networks/blob/master/body_part_segmentation/create_pose_maps.py
you will find the required information in this file.
for training the action recognition network you need to calculate volume mean of 16 frames. We will provide this in the coming days.
